import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, ChevronDown, ChevronRight, ChevronLeft, X, Settings, Palette, Image as ImageIcon, SlidersHorizontal, Grid2X2, Music2, Plus, Play, Pause, SkipBack, SkipForward, Upload, Monitor, Moon, Sun, Sparkles, Eye, Trash2, Pencil, GripVertical, ExternalLink } from 'lucide-react';
import './styles.css';

type Shortcut = { id:string; name:string; url:string; icon?:string };
type Background = { type:'none'|'image'|'video'; url?:string; name?:string; fit:'cover'|'contain'; dim:number; autoplay:boolean; loop:boolean; muted:boolean };
type SettingsState = { theme:'dark'|'light'|'system'; accent:string; blur:number; glow:boolean; showClock:boolean; showGreeting:boolean; showDate:boolean; background:Background; engine:string; suggestions:boolean; newTab:boolean; spotifyClientId:string };
type Track = { title:string; artist:string; album:string; image:string; progress:number; duration:number; isPlaying:boolean };

const engines: Record<string,string> = { Google:'https://www.google.com/search?q=', Bing:'https://www.bing.com/search?q=', DuckDuckGo:'https://duckduckgo.com/?q=', YouTube:'https://www.youtube.com/results?search_query=' };
const defaultSettings:SettingsState = { theme:'dark', accent:'#668dff', blur:20, glow:true, showClock:true, showGreeting:true, showDate:true, background:{type:'none',fit:'cover',dim:34,autoplay:true,loop:true,muted:true}, engine:'Google', suggestions:true, newTab:true, spotifyClientId:'' };
const load = <T,>(key:string, fallback:T):T => { try { const v=localStorage.getItem(key); return v ? JSON.parse(v) : fallback; } catch { return fallback; } };
const icons:Record<string,string> = { Google:'https://www.google.com/favicon.ico', YouTube:'https://www.youtube.com/favicon.ico', GitHub:'https://github.com/favicon.ico', Notion:'https://www.notion.so/images/favicon.ico', ChatGPT:'https://chatgpt.com/favicon.ico', Gmail:'https://ssl.gstatic.com/ui/v1/icons/mail/rfr/gmail.ico' };

function App(){
 const [settings,setSettings]=useState(()=>load('lumen-settings',defaultSettings));
 const [shortcuts,setShortcuts]=useState<Shortcut[]>(()=>load('lumen-shortcuts',[]));
 const [drawer,setDrawer]=useState(false); const [section,setSection]=useState<'home'|'appearance'|'search'|'shortcuts'|'spotify'>('home');
 const [query,setQuery]=useState(''); const [clock,setClock]=useState(new Date()); const [gear,setGear]=useState(false); const [track,setTrack]=useState<Track|null>(null); const [connected,setConnected]=useState(()=>Boolean(localStorage.getItem('lumen-spotify-token')));
 const searchRef=useRef<HTMLInputElement>(null); const [editing,setEditing]=useState<Shortcut|null>(null);
 useEffect(()=>{localStorage.setItem('lumen-settings',JSON.stringify(settings)); document.documentElement.style.setProperty('--accent',settings.accent); document.documentElement.style.setProperty('--blur',`${settings.blur}px`)},[settings]);
 useEffect(()=>{localStorage.setItem('lumen-shortcuts',JSON.stringify(shortcuts))},[shortcuts]);
 useEffect(()=>{const t=setInterval(()=>setClock(new Date()),1000); return()=>clearInterval(t)},[]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();searchRef.current?.focus()} if(e.key==='Escape')setDrawer(false)}; window.addEventListener('keydown',onKey); return()=>window.removeEventListener('keydown',onKey)},[]);
 useEffect(()=>{const hash=new URLSearchParams(location.hash.replace(/^#/,'?')); const token=hash.get('access_token'); if(token){localStorage.setItem('lumen-spotify-token',token);setConnected(true);history.replaceState(null,'',location.pathname);}},[]);
 useEffect(()=>{let timer:number|undefined; const poll=async()=>{const token=localStorage.getItem('lumen-spotify-token'); if(!token){setTrack(null);return} try{const r=await fetch('https://api.spotify.com/v1/me/player',{headers:{Authorization:`Bearer ${token}`}}); if(r.status===401){localStorage.removeItem('lumen-spotify-token');setConnected(false);setTrack(null);return} if(r.status===204){setTrack(null);return} const d=await r.json(); if(!d?.item||!d.is_playing){setTrack(null);return} setTrack({title:d.item.name,artist:d.item.artists?.map((a:any)=>a.name).join(', ')||'',album:d.item.album?.name||'',image:d.item.album?.images?.[0]?.url||'',progress:d.progress_ms||0,duration:d.item.duration_ms||1,isPlaying:Boolean(d.is_playing)});}catch{setTrack(null)}}; poll(); timer=window.setInterval(poll,10000); return()=>window.clearInterval(timer)},[connected]);
 const time=clock.toLocaleTimeString([], {hour:'numeric',minute:'2-digit',hour12:true}); const seconds=String(clock.getSeconds()).padStart(2,'0'); const date=clock.toLocaleDateString([], {weekday:'long',month:'long',day:'numeric'}).toUpperCase();
 const bg=settings.background; const update=(patch:Partial<SettingsState>)=>setSettings(s=>({...s,...patch})); const updateBg=(patch:Partial<Background>)=>update({background:{...bg,...patch}});
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!query.trim())return; const url=(engines[settings.engine]||engines.Google)+encodeURIComponent(query.trim()); window.open(url,settings.newTab?'_blank':'_self');};
 const spotifyAction=async(path:string,method='POST')=>{const token=localStorage.getItem('lumen-spotify-token'); if(!token)return; await fetch(`https://api.spotify.com/v1/me/player/${path}`,{method,headers:{Authorization:`Bearer ${token}`}});};
 const beginConnect=async()=>{ if(!settings.spotifyClientId){setSection('spotify'); return} const chromeApi=(globalThis as any).chrome; const redirect=chromeApi?.identity?.getRedirectURL?.()||`${location.origin}/spotify-callback`; const state=crypto.randomUUID(); sessionStorage.setItem('lumen-spotify-state',state); const url=`https://accounts.spotify.com/authorize?client_id=${encodeURIComponent(settings.spotifyClientId)}&response_type=token&redirect_uri=${encodeURIComponent(redirect)}&scope=${encodeURIComponent('user-read-currently-playing user-read-playback-state user-modify-playback-state')}&state=${state}`; if(chromeApi?.identity?.launchWebAuthFlow){try{const callback=await new Promise<string>((resolve,reject)=>chromeApi.identity.launchWebAuthFlow({url,interactive:true},(responseUrl:string)=>{const err=chromeApi.runtime?.lastError;if(err||!responseUrl){reject(err||new Error('Spotify authorization cancelled'));return}resolve(responseUrl)})); const params=new URLSearchParams((callback.split('#')[1]||'').replace(/^#/,'?')); const token=params.get('access_token'); if(token){localStorage.setItem('lumen-spotify-token',token);setConnected(true)}}catch{setConnected(false)}}else window.location.href=url; };
 const openSection=(s:typeof section)=>{setSection(s);setDrawer(true)};
 const handleFile=(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0]; if(!file)return; const reader=new FileReader(); reader.onload=()=>updateBg({type:file.type.startsWith('video')?'video':'image',url:String(reader.result),name:file.name}); reader.readAsDataURL(file)};
 const openShortcut=(s:Shortcut)=>window.open(s.url,'_blank');
 return <main className={`lumen ${settings.theme==='light'?'light':''}`} onMouseMove={e=>{if(e.clientX>window.innerWidth-170&&e.clientY>window.innerHeight-140)setGear(true);else if(!drawer)setGear(false)}}>
   <div className="background-layer">{bg.type==='image'&&bg.url&&<img src={bg.url} style={{objectFit:bg.fit}}/>}{bg.type==='video'&&bg.url&&<video src={bg.url} autoPlay={bg.autoplay} loop={bg.loop} muted={bg.muted} playsInline style={{objectFit:bg.fit}}/>}<div className="dim" style={{opacity:bg.dim/100}}/></div>
   <div className="ambient"/>
   <section className={`hero ${drawer?'drawer-open':''}`}>
    {settings.showGreeting&&<div className="eyebrow"><span/>GOOD {clock.getHours()<12?'MORNING':clock.getHours()<18?'AFTERNOON':'EVENING'}</div>}
    {settings.showClock&&<div className="clock">{time}<small>:{seconds}</small></div>}
    {settings.showDate&&<div className="date">{date}</div>}
    <form className={`unified ${track?'playing':''}`} onSubmit={submit}>
      <div className="search-row"><Search size={25} strokeWidth={1.7}/><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search anything..."/><div className="engine"><select value={settings.engine} onChange={e=>update({engine:e.target.value})}>{Object.keys(engines).map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={16}/></div><span className="shortcut">⌘ K</span></div>
      <div className={`player ${track?'show':''}`}>{track&&<><img className="album" src={track.image}/><div className="track-meta"><strong>{track.title}</strong><span>{track.artist}</span><small><i/> Spotify</small></div><div className="progress"><div className="rail"><b style={{width:`${Math.min(100,track.progress/track.duration*100)}%`}}/></div><div><span>{fmt(track.progress)}</span><span>{fmt(track.duration)}</span></div></div><button type="button" className="icon-btn" onClick={()=>spotifyAction('previous')}><SkipBack size={22}/></button><button type="button" className="play-btn" onClick={()=>spotifyAction('pause')}><Pause size={23}/></button><button type="button" className="icon-btn" onClick={()=>spotifyAction('next')}><SkipForward size={22}/></button><div className="spotify-mark">●</div></>}</div>
    </form>
    <div className="shortcuts">{shortcuts.map(s=><button key={s.id} className="shortcut-tile" onClick={()=>openShortcut(s)}><span>{s.icon?<img src={s.icon}/>:<img src={icons[s.name]||''}/>}</span><label>{s.name}</label></button>)}<button className="shortcut-tile add" onClick={()=>{setEditing({id:'',name:'',url:''});openSection('shortcuts')}}><span><Plus size={28}/></span><label>Add</label></button></div>
   </section>
   <button className={`gear ${gear||drawer?'visible':''}`} onClick={()=>{setDrawer(true);setSection('home')}}><Settings size={20}/></button>
   {drawer&&<><div className="scrim" onClick={()=>setDrawer(false)}/><aside className="drawer"><header>{section==='home'?<><div><h2>Settings</h2><p>Customize your new tab experience</p></div></>:<><button className="back" onClick={()=>setSection('home')}><ChevronLeft/></button><div><h2>{label(section)}</h2><p>{description(section)}</p></div></>}<button className="close" onClick={()=>setDrawer(false)}><X/></button></header>{section==='home'?<SettingsIndex onOpen={openSection}/>:section==='appearance'?<Appearance settings={settings} update={update} updateBg={updateBg} handleFile={handleFile}/>:section==='search'?<SearchSettings settings={settings} update={update}/>:section==='shortcuts'?<ShortcutSettings shortcuts={shortcuts} setShortcuts={setShortcuts} editing={editing} setEditing={setEditing}/>:<SpotifySettings connected={connected} onConnect={beginConnect} onDisconnect={()=>{localStorage.removeItem('lumen-spotify-token');setConnected(false);setTrack(null)}} clientId={settings.spotifyClientId} setClientId={v=>update({spotifyClientId:v})}/>}<a className="download-extension" href="/download/lumen-extension.zip" download><ExternalLink size={15}/> Download Chrome Extension</a></aside></>}
 </main>
}
function fmt(ms:number){const sec=Math.floor(ms/1000);return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
function label(s:string){return s[0].toUpperCase()+s.slice(1)} function description(s:string){return s==='appearance'?'Customize how your new tab looks and feels':s==='search'?'Search engine and suggestions':s==='shortcuts'?'Manage your quick links':'Connect your Spotify account'}
function SettingsIndex({onOpen}:{onOpen:(s:any)=>void}){const items=[['appearance',Palette,'Appearance','Theme, colors, interface'],['search',Search,'Search','Search engine and suggestions'],['shortcuts',Grid2X2,'Shortcuts','Manage your quick links'],['spotify',Music2,'Spotify','Connect your Spotify account']];return <div className="settings-list">{items.map(([key,I,title,sub]:any)=><button className="settings-card" key={key} onClick={()=>onOpen(key)}><span className={`setting-icon ${key}`}><I size={25}/></span><span><strong>{title}</strong><small>{sub}</small></span><ChevronRight/></button>)}</div>}
function Toggle({on,onChange}:{on:boolean;onChange:(v:boolean)=>void}){return <button className={`toggle ${on?'on':''}`} onClick={()=>onChange(!on)}><i/></button>}
function Appearance({settings,update,updateBg,handleFile}:{settings:SettingsState;update:(p:Partial<SettingsState>)=>void;updateBg:(p:Partial<Background>)=>void;handleFile:(e:any)=>void}){return <div className="panel"><h3>Theme</h3><div className="seg three">{[['light',Sun],['dark',Moon],['system',Monitor]].map(([v,I]:any)=><button className={settings.theme===v?'selected':''} onClick={()=>update({theme:v})}><I size={17}/><span>{label(v)}</span></button>)}</div><h3>Accent Color</h3><div className="colors">{['#668dff','#9164ee','#e83d82','#ff9943','#14c77a','#16b5c5','#ec43d0'].map(c=><button style={{background:c}} className={settings.accent===c?'selected':''} onClick={()=>update({accent:c})}/>)}</div><h3>Background</h3><div className="seg three"><button className={settings.background.type==='image'?'selected':''} onClick={()=>updateBg({type:'image'})}><ImageIcon size={16}/>Image</button><button className={settings.background.type==='video'?'selected':''} onClick={()=>updateBg({type:'video'})}><Play size={16}/>Video</button><button onClick={()=>updateBg({type:'none'})}><Sparkles size={16}/>Blank</button></div><label className="upload"><Upload size={16}/> Change Background<input type="file" accept="image/*,video/*" onChange={handleFile}/></label><h3>Dim Background <span className="value">{settings.background.dim}%</span></h3><input className="range" type="range" min="0" max="80" value={settings.background.dim} onChange={e=>updateBg({dim:Number(e.target.value)})}/><div className="row-setting"><span><Eye size={17}/><b>Blur Effect</b><small>Apply blur to UI elements</small></span><Toggle on={settings.blur>0} onChange={v=>update({blur:v?20:0})}/></div><div className="row-setting"><span><Sparkles size={17}/><b>UI Glow</b><small>Keep the subtle edge lighting</small></span><Toggle on={settings.glow} onChange={v=>update({glow:v})}/></div><div className="row-setting"><span><Eye size={17}/><b>Show Greeting</b></span><Toggle on={settings.showGreeting} onChange={v=>update({showGreeting:v})}/></div><div className="row-setting"><span><Eye size={17}/><b>Show Time & Date</b></span><Toggle on={settings.showClock&&settings.showDate} onChange={v=>update({showClock:v,showDate:v})}/></div></div>}
function SearchSettings({settings,update}:{settings:SettingsState;update:(p:Partial<SettingsState>)=>void}){return <div className="panel"><h3>Search Engine</h3><select className="big-select" value={settings.engine} onChange={e=>update({engine:e.target.value})}>{Object.keys(engines).map(x=><option>{x}</option>)}</select><div className="row-setting"><span><b>Show Search Suggestions</b><small>Get suggestions while typing</small></span><Toggle on={settings.suggestions} onChange={v=>update({suggestions:v})}/></div><div className="row-setting"><span><b>Open Results in New Tab</b><small>Keep your new tab clean</small></span><Toggle on={settings.newTab} onChange={v=>update({newTab:v})}/></div></div>}
function SpotifySettings({connected,onConnect,onDisconnect,clientId,setClientId}:{connected:boolean;onConnect:()=>void;onDisconnect:()=>void;clientId:string;setClientId:(v:string)=>void}){return <div className="panel"><div className="spotify-connect"><span className="spotify-large">●</span><strong>{connected?'Connected':'Not connected'}</strong><p>{connected?'Your Spotify account is linked.':'Link your Spotify account to show now playing on your new tab.'}</p>{!connected&&<input className="client-input" placeholder="Spotify Client ID" value={clientId} onChange={e=>setClientId(e.target.value)}/>}<button className="connect" onClick={connected?onDisconnect:onConnect}>{connected?'Disconnect Spotify':'Connect with Spotify'}</button></div></div>}
function ShortcutSettings({shortcuts,setShortcuts,editing,setEditing}:{shortcuts:Shortcut[];setShortcuts:(x:Shortcut[])=>void;editing:Shortcut|null;setEditing:(x:Shortcut|null)=>void}){const save=()=>{if(!editing?.name||!editing.url)return;setShortcuts(editing.id?shortcuts.map(x=>x.id===editing.id?editing:x):[...shortcuts,{...editing,id:crypto.randomUUID()}]);setEditing(null)};return <div className="panel"><div className="shortcut-admin">{shortcuts.map((s,i)=><div className="admin-row" key={s.id}><GripVertical size={15}/><span>{s.icon?<img src={s.icon}/>:<img src={icons[s.name]||''}/>}</span><b>{s.name}</b><button onClick={()=>setEditing(s)}><Pencil size={15}/></button><button onClick={()=>setShortcuts(shortcuts.filter(x=>x.id!==s.id))}><Trash2 size={15}/></button></div>)}<button className="add-link" onClick={()=>setEditing({id:'',name:'',url:''})}><Plus size={16}/> Add shortcut</button></div>{editing&&<div className="edit-box"><input placeholder="Name" value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/><input placeholder="URL (https://...)" value={editing.url} onChange={e=>setEditing({...editing,url:e.target.value})}/><input placeholder="Icon URL (optional)" value={editing.icon||''} onChange={e=>setEditing({...editing,icon:e.target.value})}/><div><button onClick={()=>setEditing(null)}>Cancel</button><button className="save" onClick={save}>Save</button></div></div>}</div>}

createRoot(document.getElementById('root')!).render(<App/>);
